name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - bug
  - triage
assignees:
  - priscavdsluis
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: And did you expect to happen?
      placeholder: Please provide the steps and data to reproduce the bug.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - 0.1.0
  - type: Operating system
    id: version
    attributes:
      label: os
      description: On what operating system are you running the software?
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
